// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for the accounts command
 */
export type AccountsOptions = { 
/**
 * Show only accounts used by transactions
 */
used: boolean, 
/**
 * Show only accounts declared by account directive
 */
declared: boolean, 
/**
 * Show only accounts declared but not used
 */
unused: boolean, 
/**
 * Show only accounts used but not declared
 */
undeclared: boolean, 
/**
 * Also show account types when known
 */
types: boolean, 
/**
 * Also show where accounts were declared
 */
positions: boolean, 
/**
 * Show as account directives, for use in journals
 */
directives: boolean, 
/**
 * Find the first account matched by the pattern
 */
find: string | null, 
/**
 * Flat mode: omit N leading account name parts
 */
drop: number | null, 
/**
 * Limit depth of accounts shown
 */
depth: number | null, 
/**
 * Begin date filter
 */
begin: string | null, 
/**
 * End date filter
 */
end: string | null, 
/**
 * Period expression
 */
period: string | null, 
/**
 * Include only unmarked postings/transactions
 */
unmarked: boolean, 
/**
 * Include only pending postings/transactions
 */
pending: boolean, 
/**
 * Include only cleared postings/transactions
 */
cleared: boolean, 
/**
 * Include only non-virtual postings
 */
real: boolean, 
/**
 * Show zero items (normally hidden)
 */
empty: boolean, 
/**
 * Query patterns to filter accounts
 */
queries: Array<string>, };
