// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Amount display style
 */
export type AmountStyle = { commodity_side: string, commodity_spaced: boolean, decimal_mark: string | null, digit_groups: string | null, precision: number, rounding: string, };
