// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Amount style information
 */
export type AmountStyle = { ascommodityside: string, ascommodityspaced: boolean, asdecimalmark: string | null, asdigitgroups: string | null, asprecision: number, asrounding: string, };
