// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";

/**
 * Account information in balance report
 */
export type BalanceAccount = { 
/**
 * Full account name
 */
name: string, 
/**
 * Display name (may be shortened in tree mode)
 */
display_name: string, 
/**
 * Indentation level (for tree display)
 */
indent: number, 
/**
 * Account balances/amounts
 */
amounts: Array<Amount>, };
