// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for the balancesheet command
 */
export type BalanceSheetOptions = { 
/**
 * Show sum of posting amounts (default)
 */
sum: boolean, 
/**
 * Show change in period-end value
 */
valuechange: boolean, 
/**
 * Show unrealised capital gain/loss
 */
gain: boolean, 
/**
 * Accumulate from column start to end
 */
change: boolean, 
/**
 * Accumulate from report start to column end
 */
cumulative: boolean, 
/**
 * Accumulate from journal start to column end (default for balancesheet)
 */
historical: boolean, 
/**
 * Show accounts as flat list (default)
 */
flat: boolean, 
/**
 * Show accounts as tree
 */
tree: boolean, 
/**
 * Omit N leading account name parts
 */
drop: number | null, 
/**
 * Include non-parent declared accounts
 */
declared: boolean, 
/**
 * Show row average column
 */
average: boolean, 
/**
 * Show row total column
 */
row_total: boolean, 
/**
 * Display only row summaries
 */
summary_only: boolean, 
/**
 * Omit the final total row
 */
no_total: boolean, 
/**
 * Don't squash boring parent accounts
 */
no_elide: boolean, 
/**
 * Sort by amount instead of account name
 */
sort_amount: boolean, 
/**
 * Express values as percentage of column total
 */
percent: boolean, 
/**
 * Layout mode: wide, tall, bare
 */
layout: string | null, 
/**
 * Daily periods
 */
daily: boolean, 
/**
 * Weekly periods
 */
weekly: boolean, 
/**
 * Monthly periods
 */
monthly: boolean, 
/**
 * Quarterly periods
 */
quarterly: boolean, 
/**
 * Yearly periods
 */
yearly: boolean, 
/**
 * Custom period
 */
period: string | null, 
/**
 * Begin date
 */
begin: string | null, 
/**
 * End date
 */
end: string | null, 
/**
 * Limit depth of accounts shown
 */
depth: number | null, 
/**
 * Include only unmarked postings
 */
unmarked: boolean, 
/**
 * Include only pending postings
 */
pending: boolean, 
/**
 * Include only cleared postings
 */
cleared: boolean, 
/**
 * Include only non-virtual postings
 */
real: boolean, 
/**
 * Show zero items
 */
empty: boolean, 
/**
 * Convert to cost basis
 */
cost: boolean, 
/**
 * Convert to market value at period end
 */
market: boolean, 
/**
 * Convert to specific commodity
 */
exchange: string | null, 
/**
 * Detailed value conversion
 */
value: string | null, queries: Array<string>, };
