// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeriodDate } from "./PeriodDate";
import type { PeriodicBalanceRow } from "./PeriodicBalanceRow";

/**
 * A subreport in the balance sheet (Assets, Liabilities, etc.)
 */
export type BalanceSheetSubreport = { 
/**
 * The name of the subreport (e.g., "Assets", "Liabilities")
 */
name: string, 
/**
 * The period dates for this subreport
 */
dates: Array<PeriodDate>, 
/**
 * Account rows in this subreport
 */
rows: Array<PeriodicBalanceRow>, 
/**
 * Totals for this subreport
 */
totals: PeriodicBalanceRow | null, 
/**
 * Whether this subreport increases the overall total (true) or decreases it (false)
 * - Assets: true (increases net worth)
 * - Liabilities: false (decreases net worth)
 */
increases_total: boolean, };
