// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BalanceSheetSubreport } from "./BalanceSheetSubreport";
import type { PeriodDate } from "./PeriodDate";
import type { PeriodicBalanceRow } from "./PeriodicBalanceRow";

/**
 * Balance sheet report structure
 */
export type BalanceSheetReport = { 
/**
 * Report title
 */
title: string, 
/**
 * Period date ranges for the entire report
 */
dates: Array<PeriodDate>, 
/**
 * Subreports (Assets, Liabilities, etc.)
 */
subreports: Array<BalanceSheetSubreport>, 
/**
 * Overall totals across all subreports
 */
totals: PeriodicBalanceRow | null, };
