// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeriodicBalance } from "./PeriodicBalance";
import type { SimpleBalance } from "./SimpleBalance";

/**
 * Unified balance report that can be either simple or periodic
 */
export type BalanceReport = SimpleBalance | PeriodicBalance;
