// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrintAmount } from "./PrintAmount";
import type { SourcePosition } from "./SourcePosition";

/**
 * Balance assertion information
 */
export type BalanceAssertion = { amount: PrintAmount, inclusive: boolean, total: boolean, position: SourcePosition, };
