// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrintAmount } from "./PrintAmount";

/**
 * Balance assertion information
 */
export type BalanceAssertion = { assertion_type: string, amount: PrintAmount | null, };
