// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for the cashflow command
 */
export type CashflowOptions = { 
/**
 * Show sum of posting amounts (default)
 */
sum: boolean, 
/**
 * Show total change of value of period-end historical balances
 */
valuechange: boolean, 
/**
 * Show unrealised capital gain/loss
 */
gain: boolean, 
/**
 * Show budget comparison
 */
budget: boolean, 
/**
 * Accumulate amounts from column start to column end (default)
 */
change: boolean, 
/**
 * Accumulate amounts from report start to column end
 */
cumulative: boolean, 
/**
 * Accumulate amounts from journal start to column end
 */
historical: boolean, 
/**
 * Show accounts as a flat list (default)
 */
flat: boolean, 
/**
 * Show accounts as a tree
 */
tree: boolean, 
/**
 * Omit N leading account name parts in flat mode
 */
drop: number | null, 
/**
 * Include non-parent declared accounts
 */
declared: boolean, 
/**
 * Show a row average column
 */
average: boolean, 
/**
 * Show a row total column
 */
row_total: boolean, 
/**
 * Display only row summaries
 */
summary_only: boolean, 
/**
 * Omit the final total row
 */
no_total: boolean, 
/**
 * Don't squash boring parent accounts in tree mode
 */
no_elide: boolean, 
/**
 * Use custom line format
 */
format: string | null, 
/**
 * Sort by amount instead of account code/name
 */
sort_amount: boolean, 
/**
 * Express values in percentage of each column's total
 */
percent: boolean, 
/**
 * How to show multi-commodity amounts
 */
layout: string | null, 
/**
 * Base URL for hledger-web hyperlinks
 */
base_url: string | null, 
/**
 * Start date
 */
begin: string | null, 
/**
 * End date
 */
end: string | null, 
/**
 * Reporting period
 */
period: string | null, 
/**
 * Report by day
 */
daily: boolean, 
/**
 * Report by week
 */
weekly: boolean, 
/**
 * Report by month
 */
monthly: boolean, 
/**
 * Report by quarter
 */
quarterly: boolean, 
/**
 * Report by year
 */
yearly: boolean, 
/**
 * Depth limit for accounts
 */
depth: number | null, 
/**
 * Show empty/zero accounts
 */
empty: boolean, 
/**
 * Account query patterns
 */
query: Array<string>, };
