// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeriodicBalance } from "./PeriodicBalance";

/**
 * Cashflow subreport structure  
 */
export type CashflowSubreport = { 
/**
 * The name of the subreport (always "Cash flows" for cashflow)
 */
name: string, 
/**
 * The periodic balance data
 */
data: PeriodicBalance, 
/**
 * Whether this subreport increases the overall total (always true for cashflow)
 */
increases_total: boolean, };
