// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CashflowSubreport } from "./CashflowSubreport";
import type { PeriodDate } from "./PeriodDate";
import type { PeriodicBalanceRow } from "./PeriodicBalanceRow";

/**
 * The cashflow report structure
 */
export type CashflowReport = { 
/**
 * Report title
 */
title: string, 
/**
 * Period date ranges for the entire report
 */
dates: Array<PeriodDate>, 
/**
 * Subreports (Cash flows)
 */
subreports: Array<CashflowSubreport>, 
/**
 * Overall totals across all subreports
 */
totals: PeriodicBalanceRow | null, };
