// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IncomeStatementSubreport } from "./IncomeStatementSubreport";
import type { PeriodDate } from "./PeriodDate";
import type { PeriodicBalanceRow } from "./PeriodicBalanceRow";

/**
 * Income statement report structure
 */
export type IncomeStatementReport = { 
/**
 * Report title
 */
title: string, 
/**
 * Period date ranges for the entire report
 */
dates: Array<PeriodDate>, 
/**
 * Subreports (Revenues, Expenses)
 */
subreports: Array<IncomeStatementSubreport>, 
/**
 * Overall totals across all subreports (Net income/loss)
 */
totals: PeriodicBalanceRow | null, };
