// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";

/**
 * Row in periodic balance report
 */
export type PeriodicBalanceRow = { 
/**
 * Account name
 */
account: string, 
/**
 * Display name
 */
display_name: string, 
/**
 * Amounts for each period
 */
amounts: Array<Array<Amount>>, 
/**
 * Row total (if requested)
 */
total: Array<Amount> | null, 
/**
 * Row average (if requested)
 */
average: Array<Amount> | null, };
