// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Period date range
 */
export type PeriodDate = { 
/**
 * Start date (ISO format)
 */
start: string, 
/**
 * End date (ISO format)
 */
end: string, };
