// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeriodDate } from "./PeriodDate";
import type { PeriodicBalanceRow } from "./PeriodicBalanceRow";

/**
 * Periodic balance report (multiple periods)
 */
export type PeriodicBalance = { 
/**
 * Period date ranges
 */
dates: Array<PeriodDate>, 
/**
 * Account rows
 */
rows: Array<PeriodicBalanceRow>, 
/**
 * Totals row (unless no_total is set)
 */
totals: PeriodicBalanceRow | null, };
