// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Price information for amounts
 */
export type Price = { 
/**
 * Price commodity
 */
commodity: string, 
/**
 * Price quantity
 */
quantity: string, };
