// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BalanceAssertion } from "./BalanceAssertion";
import type { PrintAmount } from "./PrintAmount";

/**
 * Posting information in a transaction
 */
export type PrintPosting = { paccount: string, pamount: Array<PrintAmount>, pbalanceassertion: BalanceAssertion | null, pcomment: string, pdate: string | null, pdate2: string | null, poriginal: string | null, pstatus: string, ptags: Array<string>, ptransaction_: string, ptype: string, };
