// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AmountStyle } from "./AmountStyle";
import type { PrintPrice } from "./PrintPrice";
import type { Quantity } from "./Quantity";

/**
 * Amount representation in print reports
 */
export type PrintAmount = { acommodity: string, aprice: PrintPrice | null, aquantity: Quantity, astyle: AmountStyle, };
