// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrintPosting } from "./PrintPosting";
import type { SourcePosition } from "./SourcePosition";

/**
 * Complete transaction from print command
 */
export type PrintTransaction = { tcode: string, tcomment: string, tdate: string, tdate2: string | null, tdescription: string, tindex: number, tpostings: Array<PrintPosting>, tprecedingcomment: string, tsourcepos: Array<SourcePosition>, tstatus: string, ttags: Array<string>, };
