// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for the print command
 */
export type PrintOptions = { 
/**
 * Show all amounts explicitly
 */
explicit: boolean, 
/**
 * Show transaction prices even with conversion postings
 */
show_costs: boolean, 
/**
 * Display all amounts with reversed sign
 */
invert: boolean, 
/**
 * Show only newer-dated transactions added in each file since last run
 */
new: boolean, 
/**
 * Fuzzy search for one recent transaction with description closest to DESC
 */
match_desc: string | null, 
/**
 * Rounding mode for amounts
 */
round: string | null, 
/**
 * Begin date filter (inclusive: transactions on or after this date)
 */
begin: string | null, 
/**
 * End date filter (exclusive: transactions before this date)
 */
end: string | null, 
/**
 * Limit depth of accounts shown
 */
depth: number | null, 
/**
 * Include only unmarked postings
 */
unmarked: boolean, 
/**
 * Include only pending postings
 */
pending: boolean, 
/**
 * Include only cleared postings
 */
cleared: boolean, 
/**
 * Include only non-virtual postings
 */
real: boolean, 
/**
 * Show zero items
 */
empty: boolean, 
/**
 * Convert to cost basis
 */
cost: boolean, 
/**
 * Convert to market value
 */
market: boolean, 
/**
 * Convert to specific commodity
 */
exchange: string | null, 
/**
 * Detailed value conversion
 */
value: string | null, 
/**
 * Period filter
 */
period: string | null, 
/**
 * Query patterns
 */
queries: Array<string>, };
