// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrintPosting } from "./PrintPosting";
import type { SourcePosition } from "./SourcePosition";

/**
 * Transaction structure
 */
export type PrintTransaction = { index: number, date: string, date2: string | null, status: string, code: string, description: string, comment: string, tags: Array<[string, string]>, postings: Array<PrintPosting>, preceding_comment: string, source_positions: Array<SourcePosition>, };
