// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BalanceAssertion } from "./BalanceAssertion";
import type { PrintAmount } from "./PrintAmount";

/**
 * Posting structure
 */
export type PrintPosting = { account: string, amounts: Array<PrintAmount>, status: string, comment: string, tags: Array<[string, string]>, posting_type: string, date: string | null, date2: string | null, balance_assertion: BalanceAssertion | null, original: PrintPosting | null, transaction_index: string, };
