// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AmountStyle } from "./AmountStyle";
import type { Price } from "./Price";

/**
 * Amount with inline style information
 */
export type PrintAmount = { commodity: string, quantity: string, price: Price | null, style: AmountStyle, };
