// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrintAmount } from "./PrintAmount";

/**
 * Price information for amounts
 */
export type PrintPrice = { contents: PrintAmount, tag: string, };
