// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrintTransaction } from "./PrintTransaction";

/**
 * Print report containing all transactions
 */
export type PrintReport = { transactions: Array<PrintTransaction>, };
