// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for the print command
 */
export type PrintOptions = { 
/**
 * Show all amounts explicitly
 */
explicit: boolean, 
/**
 * Show transaction prices even with conversion postings
 */
show_costs: boolean, 
/**
 * Rounding mode: none, soft, hard, all
 */
round: string | null, 
/**
 * Show only newer transactions
 */
new: boolean, 
/**
 * Fuzzy search for transaction by description
 */
match_desc: string | null, 
/**
 * Begin date (inclusive)
 */
begin: string | null, 
/**
 * End date (exclusive)
 */
end: string | null, 
/**
 * Include only unmarked transactions
 */
unmarked: boolean, 
/**
 * Include only pending transactions
 */
pending: boolean, 
/**
 * Include only cleared transactions
 */
cleared: boolean, 
/**
 * Include only non-virtual postings
 */
real: boolean, 
/**
 * Show empty accounts
 */
empty: boolean, queries: Array<string>, };
