// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quantity representation with mantissa and decimal places
 */
export type Quantity = { decimalMantissa: bigint, decimalPlaces: number, floatingPoint: number, };
