// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Amount } from "./Amount";
import type { BalanceAccount } from "./BalanceAccount";

/**
 * Simple balance report (single period)
 */
export type SimpleBalance = { 
/**
 * List of accounts with their balances
 */
accounts: Array<BalanceAccount>, 
/**
 * Total amounts across all accounts
 */
totals: Array<Amount>, };
