// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source position information
 */
export type SourcePosition = { line: number, column: number, file: string, };
